import type { Metadata } from "next";
import Link from "next/link";
import "./tekla.css";
import "./gallery.css";

export const metadata: Metadata = {
  title: "Tekla Steel Detailing Service | Structural Steel Shop Drawings Provider",
  description: "Professional Tekla Structures modeling, steel detailing, fabrication drawings and shop drawing support from Shanjiang for global steel fabricators, contractors and modular building companies.",
  keywords: ["Tekla steel detailing service", "Tekla detailer outsourcing", "structural steel detailing", "steel shop drawings", "steel fabrication drawings", "Tekla Structures modeling"],
  alternates: { canonical: "https://griegojaquish-bot.github.io/tekla-steel-detailing" },
};

const services = [
  { number: "01", eyebrow: "TEKLA STRUCTURES", title: "3D steel modeling", text: "Accurate models prepared from design drawings, structural information and your project standards.", items: ["Steel frame modeling", "Connection modeling", "Assembly organization", "Model checking and clash support"] },
  { number: "02", eyebrow: "FABRICATION", title: "Fabrication drawings", text: "Clear production information organized for steel workshops and efficient material preparation.", items: ["Single part drawings", "Assembly drawings", "Material lists and bolt information", "Welding and cutting details"] },
  { number: "03", eyebrow: "SHOP DRAWINGS", title: "Production-ready support", text: "Detailing support that keeps drawing issues, revisions and fabrication questions moving together.", items: ["Drawing issue organization", "Revision coordination", "Workshop clarification support", "Installation-aware detailing"] },
];
const industries = [["01", "Industrial buildings", "Steel workshops, warehouses and factory buildings."], ["02", "Commercial buildings", "Offices, shopping centers and public buildings."], ["03", "Modular buildings", "Prefabricated houses, site accommodation and temporary buildings."], ["04", "Bridge & heavy steel", "Steel components, complex structures and custom fabrication projects."]];
const workflow = [["01", "Design drawings"], ["02", "Tekla 3D model"], ["03", "Detail checking"], ["04", "Fabrication drawings"], ["05", "Workshop support"]];
const projectExperience = [["STEEL STRUCTURE WORKSHOP", "Tekla modeling, shop drawings and fabrication details."], ["MODULAR BUILDING PROJECT", "Structural detailing, component drawings and production support."], ["COMPLEX STEEL STRUCTURE", "3D modeling, connection detailing and manufacturing drawings."]];

export default function TeklaSteelDetailingPage() {
  return <main className="teklaPage">
    <header className="teklaHeader"><Link className="teklaBrand" href="/en" aria-label="Shanjiang home"><b>SJ</b><span>SHANJIANG<small>MODULAR HOUSING</small></span></Link><nav aria-label="Tekla service navigation"><Link href="/en">Home</Link><Link href="/en/factory">Factory &amp; Projects</Link><Link href="#services">Services</Link><Link className="teklaNavCta" href="#contact">Request a quote <i>→</i></Link></nav></header>

    <section className="teklaHero"><div className="teklaHeroCopy"><p className="teklaKicker">TEKLA STEEL DETAILING SERVICE</p><h1>Professional steel detailing support, <em>built for production.</em></h1><p className="teklaLead">Shanjiang supports global steel fabricators, contractors and modular building companies with accurate Tekla modeling, fabrication drawings and shop drawing solutions.</p><div className="teklaExperience"><div><strong>20</strong><span>years in steel structure work</span></div><div><strong>7</strong><span>years using Tekla Structures</span></div></div><div className="teklaActions"><Link className="teklaButton primary" href="#contact">Request a quote <b>→</b></Link><Link className="teklaButton secondary" href="#services">Explore services</Link></div></div><div className="teklaModelBoard" aria-label="Tekla steel detailing workflow illustration"><div className="modelTopline"><span>TEKLA / MODEL REVIEW</span><span>STEEL READY</span></div><div className="modelFrame"><div className="modelRoof" /><div className="modelColumns"><i /><i /><i /><i /><i /></div><div className="modelFloor" /><span className="modelLabel labelA">3D MODEL</span><span className="modelLabel labelB">DETAIL</span><span className="modelLabel labelC">FABRICATION</span></div><p>From engineering information to workshop-ready drawing packages.</p></div></section>

    <section className="teklaProof" aria-label="Experience highlights"><div><strong>20</strong><span>years of steel structure experience</span></div><div><strong>7</strong><span>years of Tekla modeling experience</span></div><div><strong>01</strong><span>practical partner from model to shop</span></div><div><strong>GLOBAL</strong><span>support for overseas project teams</span></div></section>

    <section id="services" className="teklaSection servicesSection"><div className="teklaSectionHeading"><div><p className="teklaKicker">OUR STEEL DETAILING SERVICES</p><h2>Detailing that keeps <em>production moving.</em></h2></div><p>We combine practical steel structure knowledge with a disciplined Tekla workflow, so the model and the drawing package stay useful on the shop floor.</p></div><div className="serviceGrid">{services.map((service) => <article className="serviceCard" key={service.number}><span className="serviceNumber">{service.number}</span><p className="serviceEyebrow">{service.eyebrow}</p><h3>{service.title}</h3><p>{service.text}</p><ul>{service.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section className="teklaGallery"><div className="teklaSectionHeading compact"><div><p className="teklaKicker">TEKLA MODEL &amp; PROJECT SAMPLES</p><h2>From model review to <em>site-ready detail.</em></h2></div><p>Selected examples from our Tekla image library: steel framing, curved structures, stair details, project views and engineering drawings.</p></div><div className="teklaImageGrid"><figure className="imageFeature"><img src="/tekla/tekla-bridge-model.jpg" alt="Tekla 3D model of a curved steel bridge structure" loading="lazy" decoding="async" /><figcaption><span>01 / TEKLA MODEL</span><b>Curved steel structure</b></figcaption></figure><figure><img src="/tekla/tekla-roof-model.jpg" alt="Tekla 3D model of a steel roof frame" loading="lazy" decoding="async" /><figcaption><span>02 / FRAME MODEL</span><b>Steel roof modeling</b></figcaption></figure><figure><img src="/tekla/tekla-stair-detail.jpg" alt="Tekla stair and connection detailing" loading="lazy" decoding="async" /><figcaption><span>03 / DETAIL</span><b>Stair and platform detail</b></figcaption></figure><figure><img src="/tekla/tekla-steel-frame.jpg" alt="Steel frame installation at a construction site" loading="lazy" decoding="async" /><figcaption><span>04 / SITE REFERENCE</span><b>Fabrication and installation context</b></figcaption></figure><figure><img src="/tekla/tekla-project-visual.jpg" alt="Visual study of a curved steel project" loading="lazy" decoding="async" /><figcaption><span>05 / PROJECT VIEW</span><b>Complex steel geometry</b></figcaption></figure><figure><img src="/tekla/tekla-drawing.jpg" alt="Engineering drawing for a curved steel structure" loading="lazy" decoding="async" /><figcaption><span>06 / DRAWING</span><b>Drawing-based coordination</b></figcaption></figure></div></section>

    <section className="teklaIndustries"><div className="teklaSectionHeading compact"><div><p className="teklaKicker">PROJECT TYPES</p><h2>Built around your <em>steel scope.</em></h2></div><p>Support for project teams that need reliable detailing capacity without adding permanent overhead.</p></div><div className="industryGrid">{industries.map(([number, title, text]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p><span>STEEL DETAILING SUPPORT</span></article>)}</div></section>

    <section className="teklaWhy"><div className="whyCopy"><p className="teklaKicker">WHY CHOOSE SHANJIANG?</p><h2>Real engineering experience, <em>not only software operation.</em></h2><p>We understand the relationship between drawings, fabrication, transport and installation. That practical view helps us prepare details that are easier to check, produce and use on site.</p><ul><li>Fabrication requirements</li><li>Installation process</li><li>Construction difficulties</li><li>Practical engineering solutions</li></ul></div><div className="workflowPanel"><p className="teklaKicker">A CLEAR TEKLA WORKFLOW</p><div className="workflowList">{workflow.map(([number, title]) => <div key={number}><b>{number}</b><span>{title}</span>{number !== "05" && <i>↓</i>}</div>)}</div></div></section>

    <section className="teklaSection experienceSection"><div className="teklaSectionHeading compact"><div><p className="teklaKicker">PROJECT EXPERIENCE</p><h2>Useful output for <em>real projects.</em></h2></div><p>Our background covers workshop production, modular building delivery and complex steel structure applications.</p></div><div className="experienceGrid">{projectExperience.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="teklaSoftware"><div><p className="teklaKicker">SOFTWARE CAPABILITY</p><h2>Organized for accurate <em>delivery.</em></h2></div><div className="softwareList"><span>Tekla Structures</span><span>AutoCAD</span><span>3D modeling workflow</span><span>Engineering drawing management</span></div></section>

    <section id="contact" className="teklaContact"><div className="contactCopy"><p className="teklaKicker">WORK WITH US</p><h2>Send the drawings. <em>Start the conversation.</em></h2><p>Looking for a reliable Tekla detailing partner? Send us your structural drawings, project requirements, required standards and delivery schedule. We will review the scope and provide initial feedback.</p><div className="contactInfo"><a href="mailto:13120056@qq.com?subject=Tekla%20steel%20detailing%20enquiry">13120056@qq.com</a><a href="tel:13539957289">+86 135 3995 7289</a></div></div><div className="contactCard"><p>To request a quotation, please include:</p><ul><li>Structural drawings and project type</li><li>Required standards and deliverables</li><li>Estimated quantity or steel tonnage</li><li>Target delivery schedule</li></ul><a className="teklaButton dark" href="mailto:13120056@qq.com?subject=Tekla%20steel%20detailing%20enquiry">Email Shanjiang <b>→</b></a></div></section>

    <footer className="teklaFooter"><Link className="teklaBrand" href="/en"><b>SJ</b><span>SHANJIANG<small>MODULAR HOUSING</small></span></Link><p>Tekla modeling · Steel detailing · Fabrication drawings · Shop drawings</p><span>© 2026 SHANJIANG STEEL STRUCTURE</span></footer>
  </main>;
}
