import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import "./product.css";
import ResponsiveImage from "../../../responsive-image";

type Product={name:string;tagline:string;description:string;applications:string[];details:[string,string][]};
const productData:Record<string,Product>={
  "flat-pack":{name:"Flat-Pack Container",tagline:"Standard modules, flexible project layouts.",description:"A flat-roofed modular unit built around top and bottom frames, corner posts and insulated wall panels. It is widely used for construction camps, offices, accommodation and support facilities.",applications:["Construction site camps","Temporary offices","Staff accommodation"],details:[["Typical single-unit size","Approx. 6055 × 2990 × 2895 mm"],["Structure","Flat-roof box frame with top/bottom frames and corner posts"],["Wall system","Typical 50 / 75 mm insulated sandwich panels"],["Combination","Single, linked or multi-storey layouts subject to project engineering"]]},
  "quick-assembly":{name:"Quick Assembly House",tagline:"Flat-roof modular units for rapid installation.",description:"A flat-roof quick-assembly house uses corner fittings, columns, top and bottom frames, purlins, wall panels and roof components assembled on site. The door and protected sliding window can be arranged on the same elevation.",applications:["Temporary accommodation","Site management areas","Storage and support rooms"],details:[["Structure","Flat-roof light-steel assembly frame"],["Roof build-up","Roof sheet, insulation layer and ceiling panel"],["Walls and floor","Typical 50 / 75 mm rock-wool panels and 16 mm fire-rated magnesium-oxide floor board"],["Doors and windows","Steel door and single-glazed uPVC sliding window; final layout configurable"]]},
  "site-office":{name:"K-Type Prefab House",tagline:"Modular camp buildings with pitched roofs.",description:"K-type prefab houses use a light-steel frame, bracing, sandwich-panel enclosure and pitched roof. The common planning module is 1K = 1820 mm, allowing offices, accommodation and supporting spaces to be organised efficiently.",applications:["Project offices","Meeting rooms","Integrated site camps"],details:[["Planning module","1K = 1820 mm"],["Structure","Light-steel columns, ring beams, bracing, roof trusses and purlins"],["Envelope","Colour-steel sandwich wall and roof panels"],["Layout","Single, two- or three-storey reference layouts subject to project engineering"]]},
  "site-fence":{name:"Wave Container",tagline:"A distinctive modular setting for commercial use.",description:"Creative container modules suited to retail, displays, hospitality and temporary commercial environments where visual identity matters.",applications:["Retail pop-ups","Brand displays","Commercial support spaces"],details:[["Configuration","Modular layouts for customer-facing spaces"],["Optional fittings","Exterior finish, openings and interior arrangement"],["Project support","Design discussion for the intended use"]]},
  "premium-house":{name:"U-Shaped Hip-Roof House",tagline:"A courtyard-style modular camp with a four-slope roof.",description:"This U-shaped building arranges offices, accommodation or reception spaces around a central open side. Steel columns, beams, floor framing and sandwich-panel enclosure support one- or two-level layouts with corridors, stairs and a hip roof.",applications:["Project camp offices and accommodation","Reception and meeting facilities","Management and living support spaces"],details:[["Building form","U-shaped layout; opening direction and size planned to suit the site"],["Structure","Steel columns, beams, floor framing and upper-level corridors"],["Roof system","Four-slope roof trusses, purlins, roof panels and drainage trims"],["Configuration","One- or two-storey reference layouts subject to project engineering"]]},
  "combination-1":{name:"Modular Combination 1",tagline:"Open modular reception and display spaces.",description:"Combining glazed facades, terraces and modular units to create a bright, flexible setting for welcome areas, displays and customer-facing activities.",applications:["Reception areas","Showrooms","Sales offices"],details:[["Configuration","Combined modules with open customer areas"],["Optional fittings","Glazing, terraces and interior layout"],["Project support","Layout discussion for site conditions"]]},
  "combination-2":{name:"Modular Combination 2",tagline:"Colourful, stacked modules for active places.",description:"Stacked modular forms with terraces and circulation spaces for hospitality, retail and community projects that need a distinctive presence.",applications:["Food and beverage","Retail","Community events"],details:[["Configuration","Stacked or connected module arrangements"],["Optional fittings","Exterior colour, circulation and fit-out options"],["Project support","Project-specific layout confirmation"]]},
  "combination-3":{name:"Modular Combination 3",tagline:"Multi-level modular spaces with room to grow.",description:"A layered modular solution using double-height arrangements, terraces and connections to create flexible commercial or leisure environments.",applications:["Commercial projects","Leisure spaces","Brand events"],details:[["Configuration","Connected modules for multi-level spaces"],["Optional fittings","Terraces, openings and functional layouts"],["Project support","Site and use requirements reviewed before quotation"]]}
};

const verified:Record<string,{src:string;alt:string;label:string;title:string;copy:string}>={
  "flat-pack":{src:"/product-details/flat-pack-approved.png?v=20260731-43",alt:"Flat-pack container combination project",label:"VERIFIED PROJECT IMAGE",title:"Flat-roof modules, combined with purpose.",copy:"A real project view showing linked and stacked flat-pack modules, external circulation and glazed elevations."},
  "quick-assembly":{src:"/product-details/quick-assembly-approved.png?v=20260731-43",alt:"White quick assembly house",label:"VERIFIED PRODUCT IMAGE",title:"A clean, flat-roof quick-assembly unit.",copy:"The approved product view shows the door and protected sliding window on one elevation, with a white modular enclosure."},
  "site-office":{src:"/product-details/k-type-approved.png?v=20260731-43",alt:"K-type prefab house construction",label:"VERIFIED PROJECT IMAGE",title:"The K-type frame, visible on site.",copy:"A real installation view of the K-type frame, roof structure and bracing."},
  "premium-house":{src:"/product-details/u-shaped-hip-roof-approved.png?v=20260731-43",alt:"U-shaped hip-roof house construction",label:"VERIFIED PROJECT IMAGE",title:"U-shaped structure in construction.",copy:"A real project view of the steel columns, elevated walkway, panel enclosure and four-slope roof framework."}
};
const diagrams:Record<string,string>={
  "flat-pack":"/product-details/flat-pack-structure.png",
  "quick-assembly":"/product-details/quick-assembly-structure.png",
  "site-office":"/product-details/k-type-interior.png",
  "premium-house":"/product-details/u-shaped-hip-roof-frame.png"
};

export function generateStaticParams(){return Object.keys(productData).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=productData[slug];return {title:item?`${item.name} | Shanjiang Modular Housing`:"Product | Shanjiang Modular Housing",description:item?.description};}

export default async function EnglishProductPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const item=productData[slug];if(!item)notFound();
  const hero=slug==="premium-house"?"/product-premium-house-card.png":`/product-${slug}.webp`;const photo=verified[slug];const diagram=diagrams[slug];
  return <main className={`enProduct ${slug}`}>
    <header className="enProductNav"><Link className="brand" href="/en"><b>SJ</b><span>SHANJIANG<small>MODULAR HOUSING</small></span></Link><div><Link href="/en#products">All products</Link><a href="#inquiry">Get a quote →</a></div></header>
    <section className="enProductHero"><ResponsiveImage src={hero} alt={item.name} mobileSizes="100vw"/><div><p>PRODUCT / SHANJIANG STEEL STRUCTURE</p><h1>{item.name}</h1><h2>{item.tagline}</h2><a href="#inquiry">Request product details →</a></div></section>
    <section className="enProductIntro"><div><p>PRODUCT OVERVIEW</p><h2>Made for practical,<br/>dependable delivery.</h2></div><p>{item.description}</p></section>
    {photo&&<section className="enProductVerified enProductVerifiedV2"><div className="enProductMedia"><figure><ResponsiveImage src={photo.src} alt={photo.alt} mobileSizes="(max-width: 850px) 100vw, 55vw"/><figcaption>PROJECT VIEW</figcaption></figure>{diagram&&<figure className="systemReference"><ResponsiveImage src={diagram} alt={`${item.name} system reference`} mobileSizes="(max-width: 850px) 100vw, 55vw"/><figcaption>SYSTEM REFERENCE</figcaption></figure>}</div><div className="enProductVerifiedCopy"><p>{photo.label}</p><h2>{photo.title}</h2><span>{photo.copy}</span></div></section>}
    <section className="enProductUse"><div><p>APPLICATIONS</p><h2>Where it works best</h2>{item.applications.map((application,index)=><div key={application}><b>0{index+1}</b><span>{application}</span></div>)}</div><aside className="enProductUsePanel"><small>PROJECT-LED DELIVERY</small><b>One product image.<br/>One clear story.</b><span>Final dimensions, materials and installation arrangements are confirmed against the project brief and site conditions.</span></aside></section>
    <section className="enProductSpecs"><div><p>PRODUCT INFORMATION</p><h2>Start with a clear brief.</h2><span>These are common industry reference configurations. Final dimensions, materials and performance requirements are confirmed for the intended use, site conditions and local requirements.</span></div><dl>{item.details.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
    <section id="inquiry" className="enProductInquiry"><div><p>START A PROJECT</p><h2>Need this product<br/>for your project?</h2><span>Tell us the country, quantity, intended use and preferred size. Our team will provide initial advice within 24 hours.</span></div><a href="/en#contact">Request a proposal &amp; quote →</a></section>
    <footer><Link className="brand" href="/en"><b>SJ</b><span>SHANJIANG<small>MODULAR HOUSING</small></span></Link><p>+86 135 3995 7289 · 13120056@qq.com</p></footer>
  </main>;
}
