import type { Metadata } from "next";
import QuoteForm from "./quote-form";
import { designCases, services } from "./design-data";
import "./design-home.css";

export const metadata: Metadata = { title: "山江设计服务｜钢结构设计与详图支持", description: "钢结构设计表达、Tekla 建模、详图深化与加工图支持。提交图纸需求，人工评估后报价。" };

const process = ["提交资料", "明确范围", "人工报价", "建模与深化", "校核出图", "配合交付"];

export default function Home() { return <main className="designHome">
  <header className="designNav"><a className="designBrand" href="#top"><b>SJ</b><span>山江设计服务<small>SHANJIANG DESIGN SERVICE</small></span></a><nav><a href="#services">服务内容</a><a href="#cases">案例展示</a><a href="#process">合作流程</a><a className="designNavCta" href="#contact">提交需求 <i>→</i></a></nav></header>
  <section id="top" className="designHero"><div className="designHeroImage"><video autoPlay muted loop playsInline poster="/shanjiang-hero-hd.png"><source src="/shanjiang-hero-motion.mp4" type="video/mp4" /></video></div><div className="designHeroShade" /><div className="designHeroCopy"><p>AI FDE · STEEL DESIGN · TEKLA DETAILING · SHOP DRAWINGS</p><h1>把设计，<em>落到图纸里。</em><br /><strong>把图纸，落实到工地上。</strong></h1><span>专注钢结构设计表达、Tekla 建模、AI FDE 项目协同与详图深化。<br />以清晰的模型和图纸，支持复核、加工与安装沟通。</span><div><a className="designButton primary" href="#contact">提交项目需求 <b>→</b></a><a className="designButton secondary" href="#cases">查看案例</a></div></div><div className="designHeroNote"><small>服务方式</small><b>提交需求<br />人工报价</b><span>无固定套餐，按项目范围评估</span></div></section>
  <section className="designIntro"><p className="designKicker">SHANJIANG DESIGN SERVICE</p><div><h2>不做泛泛的展示，<br /><em>只做能落地的图纸。</em></h2></div><div><p>山江设计服务面向需要设计与详图支持的钢结构项目团队。我们从资料梳理、三维建模到图纸整理，帮助设计意图更准确地传递到加工和现场环节。</p><p className="designIntroTip">请先提供图纸、项目类型、执行标准和目标交期；我们确认工作范围后人工报价。</p></div></section>
  <section id="services" className="designServices"><div className="designSectionHead"><div><p className="designKicker">WHAT WE DO</p><h2>设计与详图，<br /><em>聚焦交付。</em></h2></div><p>不提供固定价商城服务。每个项目根据资料完整度、结构复杂度、出图内容和交期单独评估。</p></div><div className="designServiceGrid">{services.map((service) => <a className="designServiceCard" href={`/services/${service.slug}`} key={service.slug}><b>{service.number}</b><small>DESIGN &amp; DETAILING</small><h3>{service.title}</h3><p>{service.summary}</p><i>查看详情 →</i></a>)}</div></section>
  <section className="aiFdeExplain"><p className="designKicker">WHAT IS AI FDE?</p><div><h2>AI FDE 不是软件，<br /><em>是一种贴着客户做交付的方式。</em></h2><p><b>FDE</b> 是 Forward Deployed Engineer（现场部署工程师）。AI FDE 不分行业：只要有真实客户需求、业务流程和交付目标，就可以先梳理任务，用 AI 辅助方案、验证结果，再落实到实际工作流中。</p></div><div className="aiFdeSteps"><article><b>01</b><span>先看客户真实任务与资料</span></article><article><b>02</b><span>再确定 AI 可参与的环节</span></article><article><b>03</b><span>验证后纳入客户交付流程</span></article></div><a href="/services/ai-fde">了解 AI FDE 客户协同 →</a></section>
  <section id="cases" className="designCases"><div className="designSectionHead"><div><p className="designKicker">SELECTED CASE IMAGES</p><h2>从形体到节点，<br /><em>看得见的深化过程。</em></h2></div><p>共 13 组工作区案例与项目空间参考图片：前 6 组为设计、模型与图纸示例，后 7 组用于展示空间组织方向；具体服务内容以项目资料评估为准。</p></div><div className="designCaseGrid">{designCases.map((item,index) => <a href={`/cases/${item.slug}`} className={index===0?"designCase feature":"designCase"} key={item.slug}><img src={item.image} alt={item.title} loading={index===0?"eager":"lazy"} /><div><small>CASE / {String(index+1).padStart(2,"0")} · {item.tag}</small><h3>{item.title}</h3><p>{item.summary}</p><i>查看详情 →</i></div></a>)}</div></section>
  <section id="process" className="designProcess"><p className="designKicker">HOW WE WORK</p><h2>先确认范围，<em>再开始深化。</em></h2><div>{process.map((item,index) => <article key={item}><b>0{index+1}</b><span>{item}</span>{index<process.length-1&&<i>→</i>}</article>)}</div></section>
  <section className="designChecklist"><div><p className="designKicker">BEFORE WE QUOTE</p><h2>为了更快评估，<br /><em>请准备这些资料。</em></h2></div><ul><li><b>01</b><span>结构图纸、建筑图或已有模型资料</span></li><li><b>02</b><span>项目类型、执行标准及需交付的图纸内容</span></li><li><b>03</b><span>预计工程量、构件范围或关键节点说明</span></li><li><b>04</b><span>目标交期、图框要求及修改配合方式</span></li></ul></section>
  <section id="contact" className="designContact"><div><p className="designKicker">START A PROJECT</p><h2>把资料发过来，<br /><em>我们先看范围。</em></h2><p>提交后由人工查看需求并联系你确认报价。紧急项目可直接电话或微信沟通。</p><div className="designContactInfo"><a href="tel:13539957289">135 3995 7289（微信同号）</a><a href="mailto:13120056@qq.com">13120056@qq.com</a></div><div className="wechatQr"><img src="/wechat-qr.png" alt="山江设计服务微信二维码，扫码添加微信" /><div><small>WECHAT / 微信咨询</small><b>扫码添加微信</b><span>添加后请发送项目资料或需求说明</span></div></div></div><QuoteForm /></section>
  <footer className="designFooter"><a className="designBrand" href="#top"><b>SJ</b><span>山江设计服务<small>SHANJIANG DESIGN SERVICE</small></span></a><p>钢结构设计表达 · Tekla 建模 · 详图深化 · 加工图支持</p><small>© 2026 SHANJIANG DESIGN SERVICE</small></footer>
</main>; }
