import type { Metadata } from "next";
import QuoteForm from "../quote-form";
import HeroMedia from "../hero-media";
import { designCases, services } from "../design-data";
import "../design-home.css";
import "../mobile-fixes.css";

export const metadata: Metadata = { title: "设计深化｜钢结构设计与详图支持", description: "钢结构设计表达、Tekla 建模、详图深化与加工图支持。提交图纸需求，人工评估后报价。" };

const designServiceSlugs = new Set(["drawing-expression", "tekla-modeling", "shop-drawings", "as-built-drawings", "engineering-blueprint-printing"]);
const designServices = services.filter((service) => designServiceSlugs.has(service.slug));
const process = ["提交资料", "明确范围", "人工报价", "建模与深化", "校核出图", "配合交付"];
const faqs = [["资料不全可以开始吗？", "可以。先把现有图纸、草图、照片或项目说明发来，我们先判断能否开展及还需补充哪些资料。"], ["怎样报价？", "不设固定套餐。根据资料完整度、结构复杂度、交付内容、修改配合和目标交期人工评估。"], ["通常能交付什么？", "按服务范围提供模型、构件图、装配图、材料信息或沟通图；最终以项目确认清单为准。"], ["是否支持急单和修改？", "请在提交时说明目标交期。我们会先评估可行性；修改范围与配合方式在开始前一并确认。"], ["工程责任如何划分？", "设计、建模和图纸服务均以确认资料为依据；结构计算、现场条件及最终工程决定须由项目相关方和专业人员复核确认。"]];

export default function DesignDetailing() { return <main className="designHome">
  <header className="designNav"><a className="designBrand" href="/"><b>SJ</b><span>山江设计深化<small>DESIGN DETAILING</small></span></a><nav><a href="/">两大业务</a><a href="#services">服务内容</a><a href="#cases">案例展示</a><a className="designNavCta" href="#contact">提交需求 <i>→</i></a></nav></header>
  <section id="top" className="designHero"><HeroMedia /><div className="designHeroShade" /><div className="designHeroCopy"><p>STEEL DESIGN · TEKLA DETAILING · SHOP DRAWINGS</p><h1>把设计，<em>落到图纸里。</em><br /><strong>把图纸，落实到工地上。</strong></h1><span>专注钢结构设计表达、Tekla 建模与详图深化。<br />以清晰的模型和图纸，支持复核、加工与安装沟通。</span><div><a className="designButton primary" href="#contact">提交设计需求 <b>→</b></a><a className="designButton secondary" href="#cases">查看案例</a></div></div><div className="designHeroNote"><small>DESIGN SERVICE</small><b>提交需求<br />人工报价</b><span>无固定套餐，按项目范围评估</span></div></section>
  <section className="designIntro"><p className="designKicker">SHANJIANG DESIGN DETAILING</p><div><h2>不做泛泛的展示，<br /><em>只做能落地的图纸。</em></h2></div><div><p>设计深化板块面向需要设计与详图支持的钢结构项目团队。我们从资料梳理、三维建模到图纸整理，帮助设计意图更准确地传递到加工和现场环节。</p><p className="designIntroTip">请先提供图纸、项目类型、执行标准和目标交期；我们确认工作范围后人工报价。</p></div></section>
  <section className="designIntroVideo" aria-labelledby="intro-video-title"><div><p className="designKicker">INTRODUCTION VIDEO</p><h2 id="intro-video-title">半分钟，<em>认识设计深化服务。</em></h2><p>从设计表达、Tekla 建模到详图深化与加工图支持，我们围绕真实项目资料，整理成能继续推进的模型和图纸。</p></div><video controls playsInline preload="none" poster="/shanjiang-intro-poster.webp" aria-label="山江设计深化中文介绍视频"><source media="(max-width: 850px)" src="/shanjiang-design-service-intro-mobile-fast-v2.mp4" type="video/mp4" /><source src="/shanjiang-design-service-intro-v3.mp4" type="video/mp4" />您的浏览器暂不支持视频播放。</video></section>
  <section id="services" className="designServices"><div className="designSectionHead"><div><p className="designKicker">DESIGN SERVICES</p><h2>设计与详图，<br /><em>聚焦交付。</em></h2></div><p>本板块只展示设计深化业务。每个项目根据资料完整度、结构复杂度、出图内容和交期单独评估。</p></div><div className="designServiceGrid">{designServices.map((service) => <a className="designServiceCard" href={`/services/${service.slug}`} key={service.slug}><b>{service.number}</b><small>DESIGN &amp; DETAILING</small><h3>{service.title}</h3><p>{service.summary}</p><i>查看详情 →</i></a>)}</div></section>
  <section id="cases" className="designCases"><div className="designSectionHead"><div><p className="designKicker">SELECTED CASE IMAGES</p><h2>从形体到节点，<br /><em>看得见的深化过程。</em></h2></div><p>案例用于展示设计、模型、图纸与空间组织方向；具体服务内容以项目资料评估为准。</p></div><div className="designCaseGrid">{designCases.map((item,index) => <a href={`/cases/${item.slug}`} className={index===0?"designCase feature":"designCase"} key={item.slug}><picture><source media="(max-width: 850px)" srcSet={item.mobileImage ?? item.image} /><img src={item.image} alt={item.title} loading={index===0?"eager":"lazy"} decoding="async" /></picture><div><small>CASE / {String(index+1).padStart(2,"0")} · {item.tag}</small><h3>{item.title}</h3><p>{item.summary}</p><i>查看详情 →</i></div></a>)}</div></section>
  <section id="process" className="designProcess"><p className="designKicker">HOW WE WORK</p><h2>先确认范围，<em>再开始深化。</em></h2><div>{process.map((item,index) => <article key={item}><b>0{index+1}</b><span>{item}</span>{index<process.length-1&&<i>→</i>}</article>)}</div></section>
  <section className="designChecklist"><div><p className="designKicker">BEFORE WE QUOTE</p><h2>为了更快评估，<br /><em>请准备这些资料。</em></h2></div><ul><li><b>01</b><span>结构图纸、建筑图或已有模型资料</span></li><li><b>02</b><span>项目类型、执行标准及需交付的图纸内容</span></li><li><b>03</b><span>预计工程量、构件范围或关键节点说明</span></li><li><b>04</b><span>目标交期、图框要求及修改配合方式</span></li></ul></section>
  <section className="designFaq"><div><p className="designKicker">DESIGN FAQ</p><h2>开始之前，<br /><em>先把常见问题说清楚。</em></h2></div><div>{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary><b>0{index + 1}</b>{question}<i>+</i></summary><p>{answer}</p></details>)}</div></section>
  <section id="contact" className="designContact"><div><p className="designKicker">START A DESIGN PROJECT</p><h2>把图纸发过来，<br /><em>我们先看范围。</em></h2><p>提交后由人工查看需求并联系你确认报价。紧急项目可直接电话或微信沟通。</p><div className="designContactInfo"><a href="tel:13539957289">135 3995 7289（微信同号）</a><a href="mailto:13120056@qq.com">13120056@qq.com</a></div><div className="wechatQr"><img src="/wechat-qr-v2.png" alt="山江设计服务微信二维码，扫码添加微信" width="193" height="193" loading="eager" decoding="sync" /><div><small>WECHAT / 设计深化咨询</small><b>扫码添加微信</b><span>添加后请发送项目图纸或需求说明</span></div></div></div><QuoteForm /></section>
  <aside className="mobileQuick" aria-label="设计深化快速联系"><a href="/">两大业务</a><a href="#cases">查看案例</a><a href="#contact">提交需求</a></aside>
  <footer className="designFooter"><a className="designBrand" href="/"><b>SJ</b><span>山江设计深化<small>DESIGN DETAILING</small></span></a><p>方案表达 · Tekla 建模 · 详图深化 · 加工图支持</p><small>© 2026 SHANJIANG DESIGN SERVICE</small></footer>
</main>; }
